name: Deploy

on:
  workflow_run:
    workflows: ["Compile"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}
        repository: ${{ github.event.workflow_run.head_repository.full_name }}

    - name: Download compiled artifact
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: build-output
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build-output
        publish_branch: gh-pages
        exclude_assets: ''
